#!/bin/bash

set -e

if ! command -v uv >/dev/null 2>&1; then
    echo "Error: uv is required but is not installed. Install the distribution uv package before configuring AppRun." >&2
    exit 1
fi


# files
orig_files_map_to=(
    "apprun"
    "apprun-package"
    "apprunx-thumbnailer"
    "dictionary"
)

for file in "${orig_files_map_to[@]}"; do
    if [ -f "/usr/bin/${file}.py" ]; then
        chmod +x "/usr/bin/${file}.py"
        ln -sf "/usr/bin/${file}.py" "/usr/bin/${file}"
    elif [ -f "/usr/bin/${file}.sh" ]; then
        chmod +x "/usr/bin/${file}.sh"
        ln -sf "/usr/bin/${file}.sh" "/usr/bin/${file}"
    else
        echo "Error: ${file} was not found in /usr/bin/"
        exit 1
    fi
done

# Backward compatibility for 3.0~3.2pre1
ln -fs "/usr/bin/apprun" "/usr/bin/apprun3"
ln -fs "/usr/bin/apprun-package" "/usr/bin/apprun3-package"

/usr/bin/apprun3 --install-as-service=simple,graphical.target+systemd-user-sessions.service /usr/lib/AppRun/AppRunDropInService.apprunx

# Link AppContext to global python dist lib
if [ -f "/usr/lib/python3/dist-packages/AppContext.py" ]; then
	rm -f "/usr/lib/python3/dist-packages/AppContext.py"
fi
ln -fs "/usr/lib/AppRun/libs/AppContext.py" "/usr/lib/python3/dist-packages/AppContext.py"

# Update the MIME database and icon caches, and clear thumbnail cache
set +e
update-mime-database /usr/share/mime
update-icon-caches /usr/share/icons
update-desktop-database /usr/share/applications
xdg-mime default apprun3.desktop application/x-apprunx

echo "Please restart Nautilus using 'nautilus -q && nautilus &' to apply the changes."
