#!/bin/bash

/usr/bin/apprun3 --uninstall-as-service /usr/lib/AppRun/AppRunDropinService.apprunx


lns=(
    "/usr/local/bin/apprun"
    "/usr/local/bin/appid"
    "/usr/local/bin/apprun-prepare"
    "/usr/local/bin/apprunutil"
    "/usr/local/bin/dictionary"
    "/usr/bin/apprun"
    "/usr/bin/appid"
    "/usr/bin/apprun-prepare"
    "/usr/bin/apprunutil"
    "/usr/bin/dictionary"
    "/usr/bin/apprun3"
    "/usr/bin/apprun-package"
    "/usr/bin/apprun3-package"
)

for file in "${lns[@]}"; do
    if [ -L "${file}" ]; then
        rm -f "${file}"
    fi
done

systemctl stop apprundropin.service
systemctl disable apprundropin.service
