#!/bin/bash

/usr/bin/apprun3 --uninstall-as-service /usr/lib/AppRun/AppRunDropInService.apprunx


lns=(
    "/usr/bin/apprun"
    "/usr/bin/dictionary"
    "/usr/bin/apprun3"
    "/usr/bin/apprun-package"
    "/usr/bin/apprun3-package"
)

for file in "${lns[@]}"; do
    if [ -L "${file}" ]; then
        rm -f "${file}"
    fi
done
